# Credit Risk Resampling Techniques

## Initial Imports

In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from imblearn.ensemble import BalancedRandomForestClassifier
from imblearn.ensemble import EasyEnsembleClassifier
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import ClusterCentroids
from imblearn.combine import SMOTEENN

from collections import Counter

# Read the CSV into DataFrame

In [2]:
# Load the data
file_path = Path('Resources/lending_data.csv')
df = pd.read_csv(file_path)
df.head()

loan_size  interest_rate homeowner  borrower_income  debt_to_income  \
0    10700.0          7.672       own            52800        0.431818   
1     8400.0          6.692       own            43600        0.311927   
2     9000.0          6.963      rent            46100        0.349241   
3    10700.0          7.664       own            52700        0.430740   
4    10800.0          7.698  mortgage            53000        0.433962   

   num_of_accounts  derogatory_marks  total_debt loan_status  
0                5                 1       22800    low_risk  
1                3                 0       13600    low_risk  
2                3                 0       16100    low_risk  
3                5                 1       22700    low_risk  
4                5                 1       23000    low_risk

# Split the Data into Training and Testing

In [3]:
# Remove null values
df.dropna(inplace = True)

In [4]:
# Transform non-numerical columns into binary-type
df = pd.get_dummies(df)
df

loan_size  interest_rate  borrower_income  debt_to_income  \
0        10700.0          7.672            52800        0.431818   
1         8400.0          6.692            43600        0.311927   
2         9000.0          6.963            46100        0.349241   
3        10700.0          7.664            52700        0.430740   
4        10800.0          7.698            53000        0.433962   
...          ...            ...              ...             ...   
77531    19100.0         11.261            86600        0.653580   
77532    17700.0         10.662            80900        0.629172   
77533    17600.0         10.595            80300        0.626401   
77534    16300.0         10.068            75300        0.601594   
77535    15600.0          9.742            72300        0.585062   

       num_of_accounts  derogatory_marks  total_debt  homeowner_mortgage  \
0                    5                 1       22800                   0   
1                    3                 0       13600                   0   
2                    3                 0       16100                   0   
3                    5                 1       22700                   0   
4                    5                 1       23000                   1   
...                ...               ...         ...                 ...   
77531               12                 2       56600                   0   
77532               11                 2       50900                   1   
77533               11                 2       50300                   0   
77534               10                 2       45300                   1   
77535                9                 2       42300                   1   

       homeowner_own  homeowner_rent  loan_status_high_risk  \
0                  1               0                      0   
1                  1               0                      0   
2                  0               1                      0   
3                  1               0                      0   
4                  0               0                      0   
...              ...             ...                    ...   
77531              1               0                      1   
77532              0               0                      1   
77533              0               1                      1   
77534              0               0                      1   
77535              0               0                      1   

       loan_status_low_risk  
0                         1  
1                         1  
2                         1  
3                         1  
4                         1  
...                     ...  
77531                     0  
77532                     0  
77533                     0  
77534                     0  
77535                     0  

[77536 rows x 12 columns]

In [5]:
# Create our features
X = df.drop(columns=[df.columns[-1]])

# Create our target
y = df.iloc[:,-1]

In [6]:
X.describe()

loan_size  interest_rate  borrower_income  debt_to_income  \
count  77536.000000   77536.000000     77536.000000    77536.000000   
mean    9805.562577       7.292333     49221.949804        0.377318   
std     2093.223153       0.889495      8371.635077        0.081519   
min     5000.000000       5.250000     30000.000000        0.000000   
25%     8700.000000       6.825000     44800.000000        0.330357   
50%     9500.000000       7.172000     48100.000000        0.376299   
75%    10400.000000       7.528000     51400.000000        0.416342   
max    23800.000000      13.235000    105200.000000        0.714829   

       num_of_accounts  derogatory_marks    total_debt  homeowner_mortgage  \
count     77536.000000      77536.000000  77536.000000        77536.000000   
mean          3.826610          0.392308  19221.949804            0.497472   
std           1.904426          0.582086   8371.635077            0.499997   
min           0.000000          0.000000      0.000000            0.000000   
25%           3.000000          0.000000  14800.000000            0.000000   
50%           4.000000          0.000000  18100.000000            0.000000   
75%           4.000000          1.000000  21400.000000            1.000000   
max          16.000000          3.000000  75200.000000            1.000000   

       homeowner_own  homeowner_rent  loan_status_high_risk  
count   77536.000000    77536.000000           77536.000000  
mean        0.398911        0.103616               0.032243  
std         0.489678        0.304764               0.176646  
min         0.000000        0.000000               0.000000  
25%         0.000000        0.000000               0.000000  
50%         0.000000        0.000000               0.000000  
75%         1.000000        0.000000               0.000000  
max         1.000000        1.000000               1.000000

In [7]:
# Check the balance of our target values
y.value_counts()

1    75036
0     2500
Name: loan_status_low_risk, dtype: int64

In [8]:
# Create X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [9]:
# Create the StandardScaler instance
scaler = StandardScaler()

In [10]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset
X_scaler = scaler.fit(X_train)

In [11]:
# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Ensemble Learning

## Read the CSV and Perform Basic Data Cleaning

In [12]:
# Load the data
file_path = Path('Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path)

# Preview the data
df.head()

loan_amnt  int_rate  installment home_ownership  annual_inc  \
0    10500.0    0.1719       375.35           RENT     66000.0   
1    25000.0    0.2000       929.09       MORTGAGE    105000.0   
2    20000.0    0.2000       529.88       MORTGAGE     56000.0   
3    10000.0    0.1640       353.55           RENT     92000.0   
4    22000.0    0.1474       520.39       MORTGAGE     52000.0   

  verification_status   issue_d loan_status pymnt_plan    dti  ...  \
0     Source Verified  Mar-2019    low_risk          n  27.24  ...   
1            Verified  Mar-2019    low_risk          n  20.23  ...   
2            Verified  Mar-2019    low_risk          n  24.26  ...   
3            Verified  Mar-2019    low_risk          n  31.44  ...   
4        Not Verified  Mar-2019    low_risk          n  18.76  ...   

   pct_tl_nvr_dlq  percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  \
0            85.7             100.0                   0.0        0.0   
1            91.2              50.0                   1.0        0.0   
2            66.7              50.0                   0.0        0.0   
3           100.0              50.0                   1.0        0.0   
4           100.0               0.0                   0.0        0.0   

   tot_hi_cred_lim  total_bal_ex_mort total_bc_limit  \
0          65687.0            38199.0         2000.0   
1         271427.0            60641.0        41200.0   
2          60644.0            45684.0         7500.0   
3          99506.0            68784.0        19700.0   
4         219750.0            25919.0        27600.0   

   total_il_high_credit_limit  hardship_flag  debt_settlement_flag  
0                     61987.0              N                     N  
1                     49197.0              N                     N  
2                     43144.0              N                     N  
3                     76506.0              N                     N  
4                     20000.0              N                     N  

[5 rows x 86 columns]

## Split the Data into Training and Testing

In [13]:
# Remove null values
df.dropna(inplace = True)

In [14]:
# Transform non-numerical columns into binary-type
df = pd.get_dummies(df)
df

loan_amnt  int_rate  installment  annual_inc    dti  delinq_2yrs  \
0        10500.0    0.1719       375.35     66000.0  27.24          0.0   
1        25000.0    0.2000       929.09    105000.0  20.23          0.0   
2        20000.0    0.2000       529.88     56000.0  24.26          0.0   
3        10000.0    0.1640       353.55     92000.0  31.44          0.0   
4        22000.0    0.1474       520.39     52000.0  18.76          0.0   
...          ...       ...          ...         ...    ...          ...   
68812    10000.0    0.1502       346.76     26000.0   9.60          0.0   
68813    12000.0    0.2727       368.37     63000.0  29.07          0.0   
68814     5000.0    0.1992       185.62     52000.0  14.86          0.0   
68815    40000.0    0.0646      1225.24    520000.0   9.96          0.0   
68816    16000.0    0.1131       350.36     72000.0   7.02          2.0   

       inq_last_6mths  open_acc  pub_rec  revol_bal  ...  \
0                 0.0       8.0      0.0     1609.0  ...   
1                 0.0      17.0      1.0    18368.0  ...   
2                 0.0       8.0      0.0    13247.0  ...   
3                 1.0      10.0      1.0    17996.0  ...   
4                 1.0      14.0      0.0     9091.0  ...   
...               ...       ...      ...        ...  ...   
68812             0.0       9.0      0.0     2684.0  ...   
68813             0.0       8.0      0.0    13314.0  ...   
68814             0.0       5.0      1.0     3715.0  ...   
68815             1.0      21.0      0.0    59529.0  ...   
68816             0.0      12.0      1.0    11882.0  ...   

       loan_status_low_risk  pymnt_plan_n  initial_list_status_f  \
0                         1             1                      0   
1                         1             1                      0   
2                         1             1                      0   
3                         1             1                      0   
4                         1             1                      0   
...                     ...           ...                    ...   
68812                     1             1                      0   
68813                     1             1                      0   
68814                     1             1                      0   
68815                     1             1                      1   
68816                     1             1                      0   

       initial_list_status_w  next_pymnt_d_Apr-2019  next_pymnt_d_May-2019  \
0                          1                      0                      1   
1                          1                      0                      1   
2                          1                      0                      1   
3                          1                      0                      1   
4                          1                      0                      1   
...                      ...                    ...                    ...   
68812                      1                      0                      1   
68813                      1                      0                      1   
68814                      1                      0                      1   
68815                      0                      0                      1   
68816                      1                      0                      1   

       application_type_Individual  application_type_Joint App  \
0                                1                           0   
1                                1                           0   
2                                1                           0   
3                                1                           0   
4                                1                           0   
...                            ...                         ...   
68812                            1                           0   
68813                            1                           0   
68814                            1   

In [15]:
# Create our features
X = df.drop(columns="loan_status_low_risk")

# Create our target
y = df["loan_status_low_risk"]

In [16]:
X.describe()

loan_amnt      int_rate   installment    annual_inc           dti  \
count  68817.000000  68817.000000  68817.000000  6.881700e+04  68817.000000   
mean   16677.594562      0.127718    480.652863  8.821371e+04     21.778153   
std    10277.348590      0.048130    288.062432  1.155800e+05     20.199244   
min     1000.000000      0.060000     30.890000  4.000000e+01      0.000000   
25%     9000.000000      0.088100    265.730000  5.000000e+04     13.890000   
50%    15000.000000      0.118000    404.560000  7.300000e+04     19.760000   
75%    24000.000000      0.155700    648.100000  1.040000e+05     26.660000   
max    40000.000000      0.308400   1676.230000  8.797500e+06    999.000000   

        delinq_2yrs  inq_last_6mths      open_acc       pub_rec  \
count  68817.000000    68817.000000  68817.000000  68817.000000   
mean       0.217766        0.497697     12.587340      0.126030   
std        0.718367        0.758122      6.022869      0.336797   
min        0.000000        0.000000      2.000000      0.000000   
25%        0.000000        0.000000      8.000000      0.000000   
50%        0.000000        0.000000     11.000000      0.000000   
75%        0.000000        1.000000     16.000000      0.000000   
max       18.000000        5.000000     72.000000      4.000000   

           revol_bal  ...  loan_status_high_risk  pymnt_plan_n  \
count   68817.000000  ...           68817.000000       68817.0   
mean    17604.142828  ...               0.005042           1.0   
std     21835.880400  ...               0.070831           0.0   
min         0.000000  ...               0.000000           1.0   
25%      6293.000000  ...               0.000000           1.0   
50%     12068.000000  ...               0.000000           1.0   
75%     21735.000000  ...               0.000000           1.0   
max    587191.000000  ...               1.000000           1.0   

       initial_list_status_f  initial_list_status_w  next_pymnt_d_Apr-2019  \
count           68817.000000           68817.000000           68817.000000   
mean                0.123879               0.876121               0.383161   
std                 0.329446               0.329446               0.486161   
min                 0.000000               0.000000               0.000000   
25%                 0.000000               1.000000               0.000000   
50%                 0.000000               1.000000               0.000000   
75%                 0.000000               1.000000               1.000000   
max                 1.000000               1.000000               1.000000   

       next_pymnt_d_May-2019  application_type_Individual  \
count           68817.000000                 68817.000000   
mean                0.616839                     0.860340   
std                 0.486161                     0.346637   
min                 0.000000                     0.000000   
25%                 0.000000                     1.000000   
50%                 1.000000                     1.000000   
75%                 1.000000                     1.000000   
max                 1.000000                     1.000000   

       application_type_Joint App  hardship_flag_N  debt_settlement_flag_N  
count                68817.000000          68817.0                 68817.0  
mean                     0.139660              1.0                     1.0  
std                      0.346637              0.0                     0.0  
min                      0.000000              1.0                     1.0  
25%                      0.000000              1.0                     1.0  
50%                      0.000000              1.0                     1.0  
75%                      0.000000              1.0                     1.0  
max                      1.000000              1.0                     1.0  

[8 rows x 96 columns]

In [17]:
# Check the balance of our target values
y.value_counts()

1    68470
0      347
Name: loan_status_low_risk, dtype: int64

In [18]:
# Split the X and y into X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [19]:
# Create the StandardScaler instance
scaler = StandardScaler()

In [20]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset
X_scaler = scaler.fit(X_train)

In [21]:
# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Display the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier only, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [22]:
# Resample the training data with the BalancedRandomForestClassifier
brf = BalancedRandomForestClassifier(n_estimators=100, random_state=1)
brf.fit(X_train, y_train)

BalancedRandomForestClassifier(random_state=1)

In [23]:
# Calculated the balanced accuracy score
y_pred = brf.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.9989776843089146

In [24]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[   87,     0],
       [   35, 17083]], dtype=int64)

In [25]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.71      1.00      1.00      0.83      1.00      1.00        87
          1       1.00      1.00      1.00      1.00      1.00      1.00     17118

avg / total       1.00      1.00      1.00      1.00      1.00      1.00     17205



In [26]:
# List the features sorted in descending order by feature importance
importance_sorted = sorted(zip(brf.feature_importances_, X.columns), reverse=True)
importance_sorted[:10]

[(0.4319074770416764, 'loan_status_high_risk'),
 (0.048217737882456556, 'total_rec_prncp'),
 (0.04789904198551086, 'last_pymnt_amnt'),
 (0.0440165962029668, 'total_rec_int'),
 (0.04151201809415954, 'total_pymnt'),
 (0.04115171848458576, 'total_pymnt_inv'),
 (0.012016253406858933, 'int_rate'),
 (0.01086692305958722, 'mths_since_recent_inq'),
 (0.0102872715125112, 'out_prncp_inv'),
 (0.010249171606419819, 'issue_d_Jan-2019')]

### Easy Ensemble Classifier

In [27]:
# Train the Classifier
eec = EasyEnsembleClassifier(n_estimators=100, random_state=1)
eec.fit(X_train, y_train)

EasyEnsembleClassifier(n_estimators=100, random_state=1)

In [28]:
# Calculated the balanced accuracy score
y_pred = eec.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

1.0

In [29]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[   87,     0],
       [    0, 17118]], dtype=int64)

In [30]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      1.00      1.00      1.00      1.00        87
          1       1.00      1.00      1.00      1.00      1.00      1.00     17118

avg / total       1.00      1.00      1.00      1.00      1.00      1.00     17205



### Final Questions

1. Which model had the best balanced accuracy score?

    ***The model that has the best balanced accuracy score is the Easy Ensemble Classifier model.***

2. Which model had the best recall score?

    ***Both models have the same recall score.***

3. Which model had the best geometric mean score?

    ***Both models have the same geometric mean score.***

4. What are the top three features?

    ***The top three features are 'High-Risk Loan Status', 'Total Rec. Principle', and 'Last Payment Amount'.***

# Simple Logistic Regression

In [31]:
# Create a Logistic Regression Model
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [32]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.5057471264367817

In [33]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[    1,    86],
       [    0, 17118]], dtype=int64)

In [34]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.01      1.00      0.02      0.11      0.01        87
          1       1.00      1.00      0.01      1.00      0.11      0.01     17118

avg / total       1.00      1.00      0.02      0.99      0.11      0.01     17205



# Oversampling

In this section, you will compare two oversampling algorithms to determine which algorithm results in the best performance. You will oversample the data using the naive random oversampling algorithm and the SMOTE algorithm. For each algorithm, be sure to complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

### Naive Random Oversampling

In [35]:
# Resample the training data with the RandomOversampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

# View the count of target classes with Counter
Counter(y_resampled)

Counter({1: 51352, 0: 51352})

In [36]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [37]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6512221456744463

In [38]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[   57,    30],
       [ 6038, 11080]], dtype=int64)

In [39]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.01      0.66      0.65      0.02      0.65      0.42        87
          1       1.00      0.65      0.66      0.79      0.65      0.42     17118

avg / total       0.99      0.65      0.66      0.78      0.65      0.42     17205



### SMOTE Oversampling

In [40]:
# Resample the training data with SMOTE
X_resampled, y_resampled = SMOTE(random_state=1, sampling_strategy=1.0).fit_resample(
    X_train, y_train
)

# View the count of target classes with Counter
Counter(y_resampled)

Counter({1: 51352, 0: 51352})

In [41]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [42]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.640903304043737

In [43]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[   54,    33],
       [ 5801, 11317]], dtype=int64)

In [44]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.01      0.62      0.66      0.02      0.64      0.41        87
          1       1.00      0.66      0.62      0.80      0.64      0.41     17118

avg / total       0.99      0.66      0.62      0.79      0.64      0.41     17205



# Undersampling

In this section, you will test an undersampling algorithm to determine which algorithm results in the best performance compared to the oversampling algorithms above. You will undersample the data using the Cluster Centroids algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Display the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [45]:
# Resample the data using the ClusterCentroids resampler
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)

# View the count of target classes with Counter
Counter(y_resampled)

Counter({0: 260, 1: 260})

In [46]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [47]:
# Calculate the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.5133616157221075

In [48]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[  52,   35],
       [9774, 7344]], dtype=int64)

In [49]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.01      0.60      0.43      0.01      0.51      0.26        87
          1       1.00      0.43      0.60      0.60      0.51      0.25     17118

avg / total       0.99      0.43      0.60      0.60      0.51      0.25     17205



# Combination (Over and Under) Sampling

In this section, you will test a combination over- and under-sampling algorithm to determine if the algorithm results in the best performance compared to the other sampling algorithms above. You will resample the data using the SMOTEENN algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Display the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [50]:
# Resample the training data with SMOTEENN
sm = SMOTEENN(random_state=1)
X_resampled, y_resampled = sm.fit_resample(X_train, y_train)

# View the count of target classes with Counter
Counter(y_resampled)

Counter({0: 51351, 1: 46389})

In [51]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [52]:
# Calculate the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6089355427438752

In [53]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[  60,   27],
       [8076, 9042]], dtype=int64)

In [54]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.01      0.69      0.53      0.01      0.60      0.37        87
          1       1.00      0.53      0.69      0.69      0.60      0.36     17118

avg / total       0.99      0.53      0.69      0.69      0.60      0.36     17205



# Final Questions

1. Which model had the best balanced accuracy score?

   ***The model that has the best balanced accuracy score is the Naive Random Oversampling model, as well as, 
   Undersampling with the Cluster Centroids resampler.***

2. Which model had the best recall score?

    ***The model that has the best recall score is the Naive Random Oversampling model, as well as, 
   Undersampling with the Cluster Centroids resampler.***

3. Which model had the best geometric mean score?

    ***The model that has the best geometric mean score is the Naive Random Oversampling model, as well as, 
   Undersampling with the Cluster Centroids resampler.***
